---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-phex-dev
  name: letsencrypt-phex-dev
spec:
  acme:
    email: phemabot@gmail.com
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-phex-dev
    server: https://acme-v02.api.letsencrypt.org/directory
