---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.24.5
  values:
    controller:
      hostNetwork: true
      service:
        type: NodePort
        enableHttps: true
