---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: nginx-ingress
