---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: nginx-ingress
  values:
    controller.service.type: NodePort
    controller.service.nodePorts.http: 443
