---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: phema-phex
  namespace: phema
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: phema-phex
  chart:
    git: git@github.com:phema/deployments
    ref: master
    path: phex/dev/charts/phema-phex
    version: 0.1.1
  values:
    image:
      tag: 0.0.8
