{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "phema-phex.serviceAccountName" . }}
  labels:
{{ include "phema-phex.labels" . | indent 4 }}
{{- end -}}
