apiVersion: v1
kind: Service
metadata:
  name: {{ include "phema-phekb-export-viewer.fullname" . }}
  labels:
{{ include "phema-phekb-export-viewer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.uiPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "phema-phekb-export-viewer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
