{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "phema-phekb-export-viewer.serviceAccountName" . }}
  labels:
{{ include "phema-phekb-export-viewer.labels" . | indent 4 }}
{{- end -}}
