apiVersion: v1
kind: PersistentVolume
metadata:
  name: phekb-data
  namespace: phema
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /opt/phema/phekb/data
