apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phema-ingress
  namespace: phema
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-phex-dev
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: phex-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "phema-phex-realm"
spec:
  tls:
    - secretName: phex-dev-cert
      hosts:
        - phex.phema.science
  rules:
    - host: phex.phema.science
      http:
        paths:
          - path: /
            backend:
              serviceName: phema-phex
              servicePort: 8083
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: phema-phex
              servicePort: 8083
